apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-cm
data:
  admin.hcl: |+
    path "sys/mounts" {
      policy = "read"
    }

    path "sys/auth" {
      policy = "read"
    }

    path "secret/*" {
      policy = "write"
      capabilities = ["create"]
    }