apiVersion: v1
kind: Secret
metadata:
  name: vault-config
type: Opaque
stringData:
  extraconfig-from-values.hcl: |-
    disable_mlock = true
    
    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
      cluster_address = "[::]:8201"
    }
    
    storage "file" {
      path = "/vault/data"
    }